# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "webserver"
	LogPath     = "/tmp/log/webserver/server"

# Logger.
[logger]
    Path        = "/tmp/log/webserver"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    [database.primary]
        link  = "mysql:root:123123@tcp(127.0.0.1:3306)/webserver"
        debug = true
    # # Database user
    # [database.user]
    #     link = "mysql:root:123123@tcp(127.0.0.1:3306)/user"
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/webserver/sql"
        Level  = "all"
        Stdout = true